volumes:
  mysql_data:
    name: mysql_fiap

services:
  database:
    image: mysql:8.0
    restart: always
    ports: # remover porta do mysql pois só foi gerada para visualização
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - "./scripts/ini.sql:/docker-entrypoint-initdb.d/ini.sql"
#  app:
#    depends_on:
#      - database
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports: # porta da aplicação após decisão alterar
#      - 5024:5024
#    environment:
#      ASPNETCORE_URLS: http://+:5024