DROP TABLE IF EXISTS `users`;

CREATE TABLE users (
   Id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
   Nome VARCHAR(255),
   CPF VARCHAR(11),
   Email VARCHAR(255)
);

DROP TABLE IF EXISTS `orders`;

CREATE TABLE orders (
    Id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    OrderCode VARCHAR(255) NOT NULL UNIQUE,
    UserId BIGINT UNSIGNED NULL, 
    TotalPrice DECIMAL(18, 2) NOT NULL,
    Status VARCHAR(50),
    Expiration DATETIME(6) NOT NULL,
    FOREIGN KEY (UserId) REFERENCES users(Id)
);

DROP TABLE IF EXISTS `burgers`;

CREATE TABLE burgers (
     Id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
     Name VARCHAR(255),
     Description TEXT,
     Price DECIMAL(10, 2) NOT NULL,
     OrderId BIGINT UNSIGNED NULL,
     FOREIGN KEY (OrderId) REFERENCES orders(Id) ON DELETE CASCADE
);

DROP TABLE IF EXISTS `beverages`;

CREATE TABLE beverages (
   Id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
   Name VARCHAR(255),
   Description TEXT,
   Price DECIMAL(10, 2) NOT NULL,
   OrderId BIGINT UNSIGNED NULL,
   FOREIGN KEY (OrderId) REFERENCES orders(Id) ON DELETE CASCADE
);

DROP TABLE IF EXISTS `desserts`;

CREATE TABLE desserts (
  Id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(255),
  Description TEXT,
  Price DECIMAL(10, 2) NOT NULL,
  OrderId BIGINT UNSIGNED NULL,
  FOREIGN KEY (OrderId) REFERENCES orders(Id) ON DELETE CASCADE
);