DROP TABLE IF EXISTS `users`;

CREATE TABLE users (
   Id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
   Nome VARCHAR(255) NOT NULL,
   CPF VARCHAR(11) NOT NULL,
   Email VARCHAR(255) NOT NULL UNIQUE 
);

DROP TABLE IF EXISTS `orders`;
CREATE TABLE `orders` (
    Id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    OrderCode VARCHAR(255) NOT NULL UNIQUE,
    UserId BIGINT UNSIGNED NULL,
    TotalPrice DECIMAL(18, 2) NOT NULL,
    Status ENUM('Created', 'Received', 'InPreparation', 'Ready', 'Finished') NOT NULL,
    Expiration DATETIME NOT NULL,
    FOREIGN KEY (UserId) REFERENCES users(Id)
);


DROP TABLE IF EXISTS `products`;
CREATE TABLE `products` (
    Id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Description TEXT,
    Price DECIMAL(10, 2) NOT NULL,
    Quantity INT UNSIGNED NOT NULL DEFAULT 0,
    OrderId BIGINT UNSIGNED NULL,
    Type ENUM('Burger', 'Beverage', 'Dessert') NOT NULL,
    FOREIGN KEY (OrderId) REFERENCES orders(Id) ON DELETE CASCADE
);